module.exports = [{
	name: `Race Track`,
	roles: [
		`Team Owner`,
		`Driver`,
		`Engineer`,
		`Spectator`,
		`Referee`,
		`Mechanic`,
		`Food Vendor`,
		`Commentator`,
		`Bookmaker`,
		`Spectator`,
	],
}, {
	name: `Art Museum`,
	roles: [
		`Ticket Seller`,
		`Student`,
		`Visitor`,
		`Teacher`,
		`Security Guard`,
		`Painter`,
		`Art Collector`,
		`Art Critic`,
		`Photographer`,
		`Tourist`,
	],
}, {
	name: `Vineyard`,
	roles: [
		`Gardener`,
		`Gourmet Guide`,
		`Winemaker`,
		`Exporter`,
		`Butler`,
		`Wine Taster`,
		`Sommelier`,
		`Owner`,
		`Vineyard Manager`,
		`Oenologist`,
	],
}, {
	name: `Baseball Stadium`,
	roles: [
		`Pitcher`,
		`Catcher`,
		`Commentator`,
		`Spectator`,
		`Security Guard`,
		`Umpire`,
		`Food Vendor`,
		`Manager`,
		`First Baseman`,
		`Shortstop`,
		`Outfielder`,
		`Second Baseman`,
		`Third Baseman`,
		`Mascot`,
		`Team Owner`,
	],
}, {
	name: `Library`,
	roles: [
		`Old Man`,
		`Journalist`,
		`Author`,
		`Volunteer`,
		`Know-It-All`,
		`Student`,
		`Librarian`,
		`Loudmouth`,
		`Book Fanatic`,
		`Nerd`,
	],
}, {
	name: `Cat Show`,
	roles: [
		`Judge`,
		`Cat-Handler`,
		`Veterinarian`,
		`Security Guard`,
		`Cat Trainer`,
		`Crazy Cat Lady`,
		`Animal Lover`,
		`Cat Owner`,
		`Cat`,
		`Cat`,
	],
}, {
	name: `Retirement Home`,
	roles: [
		`Relative`,
		`Cribbage Player`,
		`Old Person`,
		`Nurse`,
		`Janitor`,
		`Cook`,
		`Blind Person`,
		`Psychologist`,
		`Old Person`,
		`Nurse`,
	],
}, {
	name: `Jail`,
	roles: [
		`Wrongly Accused Man`,
		`CCTV Operator`,
		`Guard`,
		`Visitor`,
		`Lawyer`,
		`Janitor`,
		`Jailkeeper`,
		`Criminal`,
		`Correctional Officer`,
		`Maniac`,
	],
}, {
	name: `Construction Site`,
	roles: [
		`Free-Roaming Toddler`,
		`Contractor`,
		`Crane Driver`,
		`Trespasser`,
		`Safety Officer`,
		`Electrician`,
		`Engineer`,
		`Architect`,
		`Construction Worker`,
		`Construction Worker`,
	],
}, {
	name: `The United Nations`,
	roles: [
		`Diplomat`,
		`Interpreter`,
		`Blowhard`,
		`Tourist`,
		`Napping Delegate`,
		`Journalist`,
		`Secretary of State`,
		`Speaker`,
		`Secretary General`,
		`Lobbyist`,
	],
}, {
	name: `Candy Factory`,
	roles: [
		`Candy Maker`,
		`Pastry Chef`,
		`Visitor`,
		`Taster`,
		`Truffle Maker`,
		`Supply Worker`,
		`Packager`,
		`Inspector`,
		`Machine Operator`,
		`Janitor`,
	],
}, {
	name: `Subway`,
	roles: [
		`Tourist`,
		`Subway Operator`,
		`Ticket Inspector`,
		`Pregnant Lady`,
		`Pickpocket`,
		`Cleaner`,
		`Businessman`,
		`Ticket Seller`,
		`Old Lady`,
		`Blind Man`,
	],
}, {
	name: `Coal Mine`,
	roles: [
		`Safety Inspector`,
		`Miner`,
		`Overseer`,
		`Dump Truck Operator`,
		`Driller`,
		`Coordinator`,
		`Blasting Engineer`,
		`Solid Waste Engineer`,
		`Worker`,
	],
}, {
	name: `Cemetery`,
	roles: [
		`Priest`,
		`Grave Robber`,
		`Poet`,
		`Mourning Person`,
		`Gatekeeper`,
		`Dead Person`,
		`Relative`,
		`Flower Seller`,
		`Grave Digger`,
		`Gothic Girl`,
	],
}, {
	name: `Rock Concert`,
	roles: [
		`Dancer`,
		`Singer`,
		`Fan`,
		`Guitarist`,
		`Drummer`,
		`Roadie`,
		`Stage Diver`,
		`Security Guard`,
		`Bassist`,
		`Sound Technician`,
	],
}, {
	name: `Jazz Club`,
	roles: [
		`Bouncer`,
		`Drummer`,
		`Pianist`,
		`Saxophonist`,
		`Singer`,
		`Jazz Fanatic`,
		`Dancer`,
		`Barman`,
		`VIP`,
		`Waiter`,
	],
}, {
	name: `Wedding`,
	roles: [
		`Ring Bearer`,
		`Groom`,
		`Bride`,
		`Officiant`,
		`Photographer`,
		`Flower Girl`,
		`Father of the Bride`,
		`Wedding Crasher`,
		`Best Man`,
		`Maid of Honor`,
		`Relative`,
	],
}, {
	name: `Gas Station`,
	roles: [
		`Car Enthusiast`,
		`Service Attendant`,
		`Service Attendant`,
		`Shopkeeper`,
		`Customer`,
		`Car Washer`,
		`Cashier`,
		`Customer`,
		`Climate Change Activist`,
		`Manager`,
	],
}, {
	name: `Harbor Docks`,
	roles: [
		`Loader`,
		`Loader`,
		`Salty Old Pirate`,
		`Captain`,
		`Sailor`,
		`Fisherman`,
		`Exporter`,
		`Cargo Overseer`,
		`Cargo Inspector`,
		`Smuggler`,
	],
}, {
	name: `Sightseeing Bus`,
	roles: [
		`Old Man`,
		`Lone Tourist`,
		`Driver`,
		`Annoying Child`,
		`Tourist`,
		`Tourist`,
		`Tourist`,
		`Tour Guide`,
		`Photographer`,
		`Lost Person`,
	],
}]
